import Head from 'next/head'

import { useRef } from 'react';

import Header from '..//components/sections/Header';
import Hero from '../components/sections/Hero';
import About from '../components/sections/About';
import Projects from '../components/sections/Projects';
import Skills from '../components/sections/Skills';
import Contact from '../components/sections/Contact';
import Footer from '../components/sections/Footer';
import ScrollButton from '../components/ScrollButton';



export default function Home() {
  const aboutRef = useRef()
  const projectsRef = useRef()
  const skillsRef = useRef()
  const contactRef = useRef()
  const headerRef = useRef()

  return (
    <>
      <Head>
        <title>Marina Oliveira - Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header headerRef = {headerRef} aboutRef = {aboutRef} projectsRef = {projectsRef} skillsRef = {skillsRef} contactRef = {contactRef} />      

      <Hero/>

      <About aboutRef = {aboutRef}/>

      <Projects projectsRef = {projectsRef}/>

      <Skills skillsRef = {skillsRef}/>

      <Contact contactRef = {contactRef}/>

      <Footer/>

      <ScrollButton headerRef = {headerRef}/>
    
    </>
  )
}
