import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Icon from '../assets/icon.png'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from '@fortawesome/fontawesome-svg-core';
import { faBarsStaggered } from '@fortawesome/free-solid-svg-icons';
import {faLinkedinIn, faGithubAlt } from '@fortawesome/free-brands-svg-icons'

import Header from '../components/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Marina Oliveira - Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>      

    <section>
      <div>
        <Image src={Icon}/>
      </div>

      <h2>Marina Oliveira</h2>
      <h3>Full Stack Web Developer</h3>

      <p>Desenvolvedora full-stack com foco no front-end e em tecnologias baseadas em JavaScript.</p>

      <div>
        <a href="">CV</a>
        <a href="">Projectos</a>
      </div>

      <div>
      <FontAwesomeIcon
        icon={faLinkedinIn}
        style={{ fontSize: 15, color: "#DAAF2A" }}
      />

      <FontAwesomeIcon
        icon={faGithubAlt}
        style={{ fontSize: 15, color: "#DAAF2A" }}
      />
       
      </div>
    </section>
    </>
  )
}
