import Head from 'next/head'

import Header from '..//components/sections/Header';
import Hero from '../components/sections/Hero';
import About from '../components/sections/About';
import Projects from '../components/sections/Projects';
import Skills from '../components/sections/Skills';
import Contact from '../components/sections/Contact';
import Footer from '../components/sections/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Marina Oliveira - Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>      

      <Hero/>

      <About/>

      <Projects/>

      <Skills/>

      <Contact/>

      <Footer/>
    
    </>
  )
}
